### ISSUE TITLE
Edits complete

### ISSUE THREAD

**Issue by jjhi11** [UGS-GIO/BLM-Minerals#1]
@arupke I added all the new layers, functionality and text to the app. Please review here https://geology.utah.gov/apps/blm_mineral/

**Comment by arupke** [comment]
Hey, Jay. I'm not seeing any of the new stuff... And the mining district and land ownership layers are not showing up...

**Comment by jjhi11** [comment]
Do a hard refresh. Ctrl + Shift + R

Let me know.

**Comment by marshallrobinson** [comment]
- [ ] @arupke, do you have some text to put in the "About" panel to describe the WSA Mineral Land Assessment layer? 
- [ ] @jjhi11, please spell "assesment" like "assessment" in the popups/legend.
- [ ] @jjhi11, please add (WSA) after "Wilderness Study Area" in the popup title.

**Comment by arupke** [comment]
@jjhi11 The hard refresh worked... Thanks! Things look good. A couple things left... We need to replace the IM download file that is accessed in the "about" popup. The new file will include the silica layer. I put a new zip file here: U:\EMP\Rupke\UMI2. The relevant file is the "Utah_IM_GIS" compressed/zip file.
Also under layer information, let's add this description under WSA Mineral Land Assessment: "Mineral resource assessment reports of BLM Wilderness Study Areas prepared by the U.S. Bureau of Mines."

**Comment by arupke** [comment]
@jjhi11 @marshallrobinson @marthajensen Thanks, y'all. Once those last few things are taken care of that's all for now. Appreciate your help. There will probably be a few more things coming down the pipeline in the next couple of months, but we can cross that bridge when we get there.
