### ISSUE TITLE
I need to add some data to this application

### ISSUE THREAD

**Issue by marthajensen** [UGS-GIO/BLM-Minerals#6]
Photos from Taylor/Stephanie need to be added to the application

Background on this project:
**April 16 email from Stephanie Mills** - "Andrew and I are trying to make sure we've got loose ends lined up for the end of the FY. One aspect of our data preservation grant was getting photos of minerals and core up on webmaps. We spoke with Jay and this seemed to be a relatively simple process, but we are fairly flat out in our group and have time budgeted for GIO - can we discuss if you have someone available?"

**Jay, Stephanie, Andrew, Marshall and I had a meeting on April 20 to discuss this project**

**Second email from Stephanie Mills _to Taylor Boden_ on April 27** -"I had a chat with GIO the other week about the final steps of getting the Crane photos and core photos on the webmaps.

For the Crane photos, once they are completed can you send Martha a spreadsheet indicating which photo goes with which mining district, and the location of the photos on the U drive? if there are photos that don't fit into a mining district let's leave those separate for now, we will worry about them later. These will go on the BLM/Mineral Resources map (https://geology.utah.gov/apps/blm_mineral/)."

**Email from Taylor Boden on May 19**-
" There are several folders with photos and two spreadsheets. Stephanie's original spreadsheet (Crane Collection Spreadsheet New) has rows that are flagged green that indicate photos were taken, and rows flagged blue that indicate photos were taken and mining districts identified. These blue flagged mineral and rock specimens were put in the other spreadsheet labeled "Crane Minerals Mining Districts.""

Location of photos and spreadsheets: Udrive/EMP/Critical Minerals and Crane Collection

**Comment by marthajensen** [comment]
The new data has been added to the application web service.  The new table, miningdistrict_photos is located at: https://webmaps.geology.utah.gov/arcgis/rest/services/Energy_Mineral/BLM_Mineral_Resources/MapServer/14
The new table  is related to the Mining District feature class (layerid 7) with a one to many relationship class (one mining district to many photos in the table).
The field names that are related are table field name "Mineral_District" to feature class field name "District"

@jjhi11 Not all mining districts have a photo. Do you need a yes/no column added in the Mining Districts feature class for coding? Also, the URL field is an incomplete string - the portion that you need  is https://geology.utah.gov/apps/  (the rest of the URL is in the field)

**Comment by jjhi11** [comment]
implemented with latest commit

**Comment by marshallrobinson** [comment]
@arupke @StephMills 

Give this a look and let us know what comments you have.
https://geology.utah.gov/apps/blm_mineral/

**Comment by marshallrobinson** [comment]
The following have broken links and will need fixed at some point: 
- [ ] https://geology.utah.gov/apps/blm_mineral/appfiles/photo/Cerargyrite_35_CraneCollection.JPG

- [ ] https://geology.utah.gov/apps/blm_mineral/appfiles/photo/Jasper_pseudomorph_after_Barite_1082_CraneCollection.JPG

- [ ] https://geology.utah.gov/apps/blm_mineral/appfiles/photo/Austinite_874_UnknownCollection.JPG

**Comment by marthajensen** [comment]
I fixed the broken links for the photos! Thanks for finding them

**Comment by marshallrobinson** [comment]
@jjhi11, after talking w/ @marthajensen, the pdfs that are attached to the mining districts are not showing right now (may be due to moving the location of the service to agol?)

**Comment by jjhi11** [comment]
@marshallrobinson oops looks like i never uploaded the finished code. should be good now

**Comment by StephMills** [comment]
Hi all, this looks really cool! @marshallrobinson We can go ahead and consider the photo stream for this map complete. Excited to have this addition, thanks so much for the great work!
