### ISSUE TITLE
Hours for FY '21

### ISSUE THREAD

**Issue by marshallrobinson** [UGS-GIO/BLM-Minerals#7]
@arupke & @StephMills, for the purpose of budgeting, approximately how many hours are meant for web services in FY '21 for this project? Grant's USGS project is asking for hundreds of hours and I want to make sure you get the amount of time you need for this project as well.

Thanks!

**Comment by StephMills** [comment]
@marshallrobinson which project specifically, UGP1? or BLM? For FY2021 UGP1 I probably only need about 80 hours from web services, mainly to help find a solution for online publishing of all the uranium files we will be scanning. You'll have to ask Andrew about BLM. I do have another 2 year project starting that will require substantial GIS digitization, probably ~250 hours over the course of the 2 years. Grant knows about this project and is aware of the GIS impact (we are digitizing a 7.5 quad). Let me know if you need more details.

**Comment by arupke** [comment]
@marshallrobinson , @StephMills , for the BLM project we budgeted about 150 hrs over the next 3 FYs (21, 22, 23) to a generic "web developer."
